version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]