version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: eco_assistant_db
    env_file:
      - .env

  adminer:
      image: adminer
      ports:
        - 8080:8080

  back:
    build: ./back
    ports:
      - 8001:8001
    env_file:
      - .env

  app:
    build: ./front
    ports:
      - 3000:3000
    env_file:
      - .env