version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: eco_assistant_db

  adminer:
      image: adminer
      ports:
        - 8080:8080

  app:
    build: .
    ports:
      - 8001:8001
      - 3000:3000
