version: '2'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: eco_assistant_db

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

  backend:
    build: ./back_end
    ports:
      - 8001:8001
