DROP TABLE IF EXISTS Calcul;
DROP TABLE IF EXISTS Dependance;
DROP TABLE IF EXISTS Constante;
DROP TABLE IF EXISTS ReponsePossible;
DROP TABLE IF EXISTS Question;
DROP TABLE IF EXISTS ReponseDonnee;
DROP TABLE IF EXISTS Projet;
DROP TABLE IF EXISTS Profil;

DROP DATABASE IF EXISTS ecoAssistant;
