name: Test, Build, Deploy
# deploy the application on server
on:
  push:
    branches: [ "recette" ]
# add on pull request accepted

env:
  MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
  MAIL_TOKEN: ${{ secrets.MAIL_TOKEN }}
  POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test
        run: mvn -B test --file pom.xml

      - name: Build
        run: mvn -B package -Dmaven.test.skip --file pom.xml

      - name: Clean before publish
        run: mvn clean

      - name: Publish & Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          
          scp: |
            '${{ secrets.SSH_SRC }}' => ${{ secrets.SSH_DIR }}
          
          last_ssh: |
            ./docker.sh
